# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Min-kyeong (Min) Cha
email: mcha39@gatech.edu
description: >- # this means to ignore newlines until "baseurl:"
 Homepage for Min-kyeong (Min) Cha, PhD student at the School of Public Policy, Georgia Institute of Technology.
#twitter_username: username
#github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
#permalink: /:categories/:title/
#paginate: 5 # amount of posts to show
#paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Min-kyeong (Min) Cha"
  avatar : "/assets/images/Min_headshot.jpeg"
  bio    : "Ph.D. student at the School of Public Policy, Georgia Institute of Technology."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:mcha39@gatech.edu"
footer:
  links:
    - label: "Email"
      icon: "fab fa-fw fa-envelope"
      url: "mailto:mcha39@gatech.edu"


defaults:
  # _pages
  - scope:
      type: liquid
    values:
      layout: single
research:
  type: liquid
  path: /research/
others:
  type: liquid
  path: /others/

